services:
  - type: web
    name: tetrias-invoicing-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    repo:
      name: TetriasTech/invoicing-app
      type: github